{
 "title": "Homework Netology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU LA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA 1 min"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA 5 min"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA 15 min"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Space Filesystem",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/\"}"
    }
   ]
  }
 ]
}